pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    }

    stages {
        stage('Clone GitHub Repository') {
            steps {
                git branch: 'branch1', url: 'https://github.com/rahulswargam/awsdevops'
            }
        }

        stage('Debug Directory') {
            steps {
                dir('terraform/projects/abmcpl') {
                    sh 'ls -la'
                }
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform/projects/abmcpl') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform/projects/abmcpl') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform/projects/abmcpl') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }

    post {
        success {
            echo 'Infrastructure Deployed Successfully'
        }

        failure {
            echo 'Build Failed'
        }
    }
}