pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('Clone GitHub Repository') {
            steps {
                git branch: 'branch1', url: 'https://github.com/rahulswargam/awsdevops'
            }
        }

        stage('Terraform Operations') {
            steps {
                dir('../terraform/projects/abmcpl') {
                    stage('Terraform Init') {
                        steps {
                            sh terraform init
                        }
                    }

                    stage('Terraform Plan') {
                        steps {
                            sh terraform plan
                        }
                    }

                    stage('Terraform Apply') {
                        steps {
                            sh terraform apply -auto-approve
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Infrastructure Deployed Successfully'
        }

        failure {
            echo 'Build Failed'
        }
    }
}